# Server Setting
server:
  port: 18000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    threads:
      min-spare: 100
      max: 100
    accesslog:
      enabled: true
      suffix: log
      prefix: access_log
      rename-on-rotate: true

# paging parameters
spring:
  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter: pageSize
        default-page-size: 20
        max-page-size: 2000
        one-indexed-parameters: false
      sort:
        sort-parameter: sortOrder

